services:
    dk_calculator.calculator:
        public: true
        class: DK\CalculatorBundle\Service\CalculatorService
        arguments: [ @dk_calculator.metadata_factory, @service_container ]

    dk_calculator.metadata.annotation_driver:
        public: true
        class: DK\CalculatorBundle\Metadata\Driver\AnnotationDriver
        arguments: [ @annotation_reader ]

    dk_calculator.metadata_factory:
        public: true
        class: Metadata\MetadataFactory
        arguments: [ @dk_calculator.metadata.annotation_driver ]

    dk_calculator.entity_listener:
        class: DK\CalculatorBundle\EventListener\EntityListener
        arguments: [ @dk_calculator.calculator ]
        tags:
            #- { name: doctrine.event_listener, event: postLoad }
            #- { name: doctrine.event_listener, event: postPersist }
            #- { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postFlush }